import os
import re
import sys

from collections import defaultdict
from collections.abc import Iterator
from datetime import datetime
from typing import Callable, TextIO, TypeVar, Optional

from chess.engine import Cp, Mate, MateGiven, Score, PovScore
from chess.pgn import FileExporter, Game, read_game
from chess import Move, Board, COLORS, BLACK, WHITE

from chancellor.parser.configuration import STARTPOS, Configuration
from chancellor.parser.position import Position


class PositionTree(object):
    """ For every position as a key keeps all possible transpositions how it was reached. For every variant it keeps
    counter of how many times it was reached. It also keeps the number of all variant so that the probability of any
    position can be calculated. """

    def __init__(self,
                 config: Configuration,
                 ):
        self._tree = defaultdict(lambda: Position())
        self._total = 0
        self._tree[STARTPOS].set_prob(1.0)
        self._tree[STARTPOS]._occurrences += 1
        self._opponent = config.get_opponent()
        self._threshold = config.get_min_prob()
        self._white_elo = config.get_white_elo()
        self._black_elo = config.get_black_elo()

    def add(self, cur_pos: str, prev_pos: str, moves: [str], ply: int, evaluation: Optional[PovScore]) -> bool:
        """ Adds a new position to the tree.

        :param cur_pos: current position in EPD format
        :param prev_pos: previous position in EPD format
        :param moves: list of moves that were played to reach the current position
        :param ply: ply depth of the current position
        :param evaluation: evaluation of the current position
        :return: True if the position was added, False if the prob threshold was not met
        """
        turn = WHITE if ply % 2 == 0 else BLACK

        prev_prob = self._tree[prev_pos].get_prob()
        move_prob = self._tree[prev_pos].make_move(moves[-1])
        cur_prob = prev_prob if turn == self._opponent else prev_prob * move_prob
        self._tree[cur_pos].add_eval(
            moves=moves,
            ply=ply,
            prob=cur_prob,
            evaluation=evaluation,
        )
        self._total += 1
        return cur_prob >= self._threshold

    def remove_unevaluated(self):
        """ Removes all positions that were not evaluated by the engine. """
        for fen, position in list(self._tree.items()):
            if not position.get_evaluation() and fen != STARTPOS:
                self._total -= position.get_occurrences()
                del self._tree[fen]

    def remove_unreachable(self):
        """ Removes all positions that are not reachable from the root. """
        reachable = set()
        self._dfs(STARTPOS, reachable)
        for fen, position in list(self._tree.items()):
            if fen not in reachable:
                self._total -= position.get_occurrences()
                del self._tree[fen]

    def _dfs(self, fen: str, reachable: set):
        """ Performs DFS on the tree and marks all reachable positions. """
        reachable.add(fen)
        move: Move
        board = Board(fen)
        for move in self._tree[fen].get_possible_moves():
            board.push(move)
            self._dfs(board.epd(), reachable)
            board.pop()

    def get_total(self):
        """ Returns the total number of positions. """
        return self._total

    def correct_probabilities(self, pos: str, prob: float):
        """ Corrects the probabilities of all positions. """
        board = Board(pos)
        for m, occurrences in self._tree[pos].get_possible_moves().items():
            move = Move.from_uci(m)
            board.push(move)
            updated_prob = min(self._tree[pos].get_prob(), prob)
            next_prob = updated_prob
            epd = board.epd()
            if updated_prob < self._threshold:
                if epd in self._tree:
                    self._total -= occurrences
                    self._tree[epd].delete_all_moves()
            else:
                self._tree[pos].set_prob(updated_prob)
                if board.turn != self._opponent:
                    next_prob = prob * self._tree[pos].get_move_prob(m)
            self.correct_probabilities(epd, next_prob)
            board.pop()

    def save_variants(self) -> int:
        """ Saves all variants to the given file. It will make moves until they are present in the tree. Once the next
        move is missed, save the whole variant."""

        board = Board(STARTPOS)
        possible_moves_stack = [list(self._tree[board.epd()].get_possible_moves().keys())]
        game = Game()
        game.headers["Event"] = "Generated by Chancellor"
        game.headers["Site"] = "Lichess"
        game.headers["Date"] = datetime.today().strftime("%Y.%m.%d")
        game.headers["Round"] = "1"
        game.headers["White"] = "Chancellor"
        game.headers["Black"] = "Lichess"
        game.headers["Result"] = "*"
        game.headers["Variant"] = "Standard"
        game.headers["WhiteElo"] = str(self._white_elo.start)
        game.headers["BlackElo"] = str(self._black_elo.start)

        node = game
        games_saved = 0
        if os.path.exists("../tree.pgn"):
            os.remove("../tree.pgn")

        while possible_moves_stack and possible_moves_stack[-1]:
            move = Move.from_uci(possible_moves_stack[-1].pop(0))
            board.push(move)
            node = node.add_main_variation(move)
            evaluation = self._tree[board.epd()].get_evaluation()
            if evaluation is not None:
                node.set_eval(evaluation)
                if board.epd() in self._tree:
                    candidates = list(self._tree[board.epd()].get_possible_moves().keys())
                    if candidates:
                        possible_moves_stack.append(candidates)
                        continue
                games_saved += 1
                directory = os.path.dirname("../games/")
                if not os.path.exists(directory):
                    os.makedirs(directory)
                with open(f"../tree.pgn", "a+") as new_pgn:
                    exporter = FileExporter(new_pgn)
                    game.accept(exporter)

            while possible_moves_stack:
                board.pop()
                move = node.move
                node = node.parent
                node.remove_variation(move)
                if not possible_moves_stack[-1]:
                    possible_moves_stack.pop()
                else:
                    break
        return games_saved

